const express = require('express')
const dotenv = require('dotenv').config()
const port = process.env.PORT || 5000
const color = require('colors')
const ConnectDB = require('./config/db')
const app = express()
 const {errorHandler} = require('./middleware/errorMiddleware')

ConnectDB()
app.use(express.json())
app.use(express.urlencoded({extented: false}))
app.use(errorHandler)
app.use('/api/goals',require('./routes/goalRoutes'))
app.use('/api/users',require('./routes/userRoutes'))
app.listen(port, () =>console.log(`server started ${port}`))